#!/bin/bash

MY_PATH=/usr/lib/calendar-maker

function copy_example() {
	if [ ! -f ./$1 ]; then
		cp $MY_PATH/example/$1 .
	fi
}

function make_empty_json() {
	if [ ! -f ./$1 ]; then
		cat > $1 << EOF
{
}
EOF
	fi
}

function copy_photos_readme() {
	if [ ! -f ./photos/00-PHOTOSREADME ]; then
		cp $MY_PATH/templates/00-PHOTOSREADME ./photos/.
	fi
}

# Create basic configuration if it doesn't exist already
echo "Updating templates..."
mkdir -p output
mkdir -p photos
copy_photos_readme
copy_example config.json
make_empty_json born.json
make_empty_json died.json
make_empty_json message.json

# Convert photos to 300 DPI and max 104x112 mm
# 300 DPI is 11.811 dots-per-millimeter
# Only photos starting with '2' are modified
# those are week photos
echo "Converting images..."
cd photos
mogrify -density 300 -resize 1228x1322 ./2* > ../output/photos.log 2>&1
mogrify -density 300 -resize 2456x1322 ./front-page.* >> ../output/photos.log 2>&1
cd ..

echo "Generating TeX..."
export NODE_PATH=$(npm root --quite -g)
node $MY_PATH/generate.js > output/generate.log 2>&1

echo "Creating PDF (may take couple minutes)..."
cd output
pdflatex output.tex > output-term.log 2>&1
pdflatex output.tex >> output-term.log 2>&1

# Generate also A4, uncomment if needed
#cp $MY_PATH/templates/output-a4.tex .
#pdflatex output-a4.tex

echo "All done."
