#!/bin/bash

MY_PATH="`dirname \"$0\"`"              # relative
MY_PATH="`( cd \"$MY_PATH\" && pwd )`"  # absolutized and normalized
if [ -z "$MY_PATH" ] ; then
	# error; for some reason, the path is not accessible
	# to the script (e.g. permissions re-evaled after suid)
	exit 1  # fail
fi

function copy_example() {
	if [ ! -f ./$1 ]; then
		cp $MY_PATH/example/$1 .
	fi
}

# Create basic configuration if it doesn't exist already
mkdir -p output
mkdir -p photos
copy_example config.json
copy_example born.json
copy_example died.json
copy_example message.json

# Convert photos to 300 DPI and max 104x112 mm
# 300 DPI is 11.811 dots-per-millimeter
cd photos
mogrify -density 300 -resize 1228x1322 *
cd ..

node $MY_PATH/generate.js
cd output
pdflatex output.tex
pdflatex output.tex
cp $MY_PATH/templates/output-a4.tex .
pdflatex output-a4.tex
