#!/bin/bash

MY_PATH=/usr/lib/calendar-maker

function copy_example() {
	if [ ! -f ./$1 ]; then
		cp $MY_PATH/example/$1 .
	fi
}

function copy_photos_readme() {
	if [ ! -f ./photos/00-PHOTOSREADME ]; then
		cp $MY_PATH/templates/00-PHOTOSREADME ./photos/.
	fi
}

# Create basic configuration if it doesn't exist already
mkdir -p output
mkdir -p photos
copy_photos_readme
copy_example config.json
copy_example born.json
copy_example died.json
copy_example message.json

# Convert photos to 300 DPI and max 104x112 mm
# 300 DPI is 11.811 dots-per-millimeter
# Only photos starting with '2' are modified
# those are week photos
cd photos
mogrify -density 300 -resize 1228x1322 ./2*
mogrify -density 300 -resize 2456x1322 ./front-page.*
cd ..

node $MY_PATH/generate.js
cd output
pdflatex output.tex
pdflatex output.tex
cp $MY_PATH/templates/output-a4.tex .
pdflatex output-a4.tex
